blueprint:
  name: "KNX: Blink"
  author: Seb Ruiz (https://github.com/sebr)
  homeassistant:
    min_version: "2025.5.0"
  description: Blink KNX indicators
  domain: script
  source_url: https://raw.githubusercontent.com/sebr/home-assistant-blueprints/main/scripts/knx-blink.yaml

fields:
  addresses:
    description: A list of KNX group addresses
    required: true
  blink_count:
    description: The number of times to blink
  blink_duration:
    description: >-
      The time (in milliseconds) to wait between blinks
    default: 500
  value_on:
    description: "The value to send when blinking on"
    default: 1
  value_off:
    description: "The value to send when blinking off"
    default: 0
sequence:
  - repeat:
      count: "{{ blink_count * 2 }}"
      sequence:
        - action: knx.send
          metadata: {}
          data:
            response: false
            address: "{{ addresses }}"
            payload: "{{ iif(repeat.index % 0, value_on, value_off) }}"
        - delay:
            hours: 0
            minutes: 0
            seconds: 0
            milliseconds: "{{ blink_duration }}"
mode: parallel
