blueprint:
  name: "KNX: Send Value"
  author: Seb Ruiz (https://github.com/sebr)
  homeassistant:
    min_version: "2025.5.0"
  description: Send a value to KNX group addresses
  domain: script
  source_url: https://raw.githubusercontent.com/sebr/home-assistant-blueprints/main/scripts/knx-send-value.yaml

fields:
  addresses:
    name: Addresses
    description: A list of KNX group addresses
    required: true
  payload:
    name: Payload
    description: The value to send to the KNX group addresses
    required: true
sequence:
  - action: knx.send
    metadata: {}
    data:
      response: false
      address: "{{ addresses }}"
      payload: "{{ payload }}"
mode: parallel
